global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8000
  - job_name: "celery"
    static_configs:
      - targets:
          - celery-worker:5555
